import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import PostsContainer from '../containers/Posts'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pezeshk Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PostsContainer />
      </main>
    </div>
  )
}
